services:
  planka:
    #image: ghcr.io/plankanban/planka:latest
    image: planka
    restart: on-failure
    volumes:
      - user-avatars:/app/public/user-avatars
      - project-background-images:/app/public/project-background-images
      - attachments:/app/private/attachments
    ports:
      - 3000:1337
    environment:
      - BASE_URL=https://planka.eedomus.com
      #- BASE_URL=http://plankanas.eedomus.com
      #- BASE_URL=http://192.168.1.21:3000
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY=d8b4b7a7c32bcb7ae4cfdf14849d8a6b65161f9680ed5fae3901b1e3a383f2d5fb412ab75b9b5557eac962a7078f89bd7a2b16f66ef792a965b3970a56be8c86
      - TRUST_PROXY=0
      # - TOKEN_EXPIRES_IN=365 # In days

      # related: https://github.com/knex/knex/issues/2354
      # As knex does not pass query parameters from the connection string we
      # have to use environment variables in order to pass the desired values, e.g.
      # - PGSSLMODE=<value>

      # Configure knex to accept SSL certificates
      # - KNEX_REJECT_UNAUTHORIZED_SSL_CERTIFICATE=false

      - DEFAULT_ADMIN_EMAIL=baptiste.vial@gadz.org # Do not remove if you want to prevent this user from being edited/deleted
      - DEFAULT_ADMIN_PASSWORD=teletazs09
      - DEFAULT_ADMIN_NAME=Administrateur
      - DEFAULT_ADMIN_USERNAME=Admin

      # - SHOW_DETAILED_AUTH_ERRORS=false # Set to true to show more detailed authentication error messages. It should not be enabled without a rate limiter for security reasons.
      # - ALLOW_ALL_TO_CREATE_PROJECTS=true

      # - S3_ENDPOINT=
      # - S3_REGION=
      # - S3_ACCESS_KEY_ID=
      # - S3_SECRET_ACCESS_KEY=
      # - S3_BUCKET=
      # - S3_FORCE_PATH_STYLE=true

      # - OIDC_ISSUER=
      # - OIDC_CLIENT_ID=
      # - OIDC_CLIENT_SECRET=
      # - OIDC_ID_TOKEN_SIGNED_RESPONSE_ALG=
      # - OIDC_USERINFO_SIGNED_RESPONSE_ALG=
      # - OIDC_SCOPES=openid email profile
      # - OIDC_RESPONSE_MODE=fragment
      # - OIDC_USE_DEFAULT_RESPONSE_MODE=true
      # - OIDC_ADMIN_ROLES=admin
      # - OIDC_CLAIMS_SOURCE=userinfo
      # - OIDC_EMAIL_ATTRIBUTE=email
      # - OIDC_NAME_ATTRIBUTE=name
      # - OIDC_USERNAME_ATTRIBUTE=preferred_username
      # - OIDC_ROLES_ATTRIBUTE=groups
      # - OIDC_IGNORE_USERNAME=true
      # - OIDC_IGNORE_ROLES=true
      # - OIDC_ENFORCED=true

      # Email Notifications (https://nodemailer.com/smtp/)
      - SMTP_HOST=smtp.webmo.fr
      - SMTP_PORT=465
      - SMTP_NAME="uscagnes-triathlon.com"
      - SMTP_SECURE=true
      - SMTP_USER=contact@uscagnes-triathlon.com
      - SMTP_PASSWORD=UCagnes20CTri*2023
      - SMTP_FROM="Planka US Cagnes Triathlon" <contact@uscagnes-triathlon.com>
      #- SMTP_TLS_REJECT_UNAUTHORIZED=false

      # Optional fields: accessToken, events, excludedEvents
      - |
        WEBHOOKS=[{
          "url": "https://uscagnes-triathlon.com/trombi/planka_webhooks.php",
          "accessToken": "notaccesstoken",
          "events": ["cardCreate", "cardUpdate", "cardDelete"],
          "excludedEvents": ["notificationCreate", "notificationUpdate"]
        }]
      # - SLACK_BOT_TOKEN=
      # - SLACK_CHANNEL_ID=

      # - GOOGLE_CHAT_WEBHOOK_URL=

      # - TELEGRAM_BOT_TOKEN=
      # - TELEGRAM_CHAT_ID=
      # - TELEGRAM_THREAD_ID=

      # labels:
      #   - 'traefik.enable=true'
      #   - 'traefik.http.routers.kanban.rule=Host(`plankanas.eedomus.com`)'
      #   - 'traefik.http.services.kanban.loadbalancer.server.port=1337'
    networks:
      - kanban_db
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    restart: on-failure
    ports:
      # Baptiste : ouverture port local, mais différent (6432) sur NAS Synology, car déjà utilisé par une autre base Postgres
      - 6432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d planka" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kanban_db
  # traefik:
  #   image: traefik
  #   restart: on-failure
  #   command:
  #     - "--providers.docker"
  #     - "--providers.docker.exposedByDefault=false"
  #     - "--providers.docker.network=traefik"
  #     - "--entrypoints.http.address=:80"
  #     - "--entrypoints.http.http.redirections.entrypoint.to=https"
  #     - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
  #     - "--entrypoints.https.address=:443"
  #     - "--entrypoints.https.http.tls.certResolver=le"
  #     - "--certificatesresolvers.le.acme.tlschallenge=true"
  #     - "--certificatesresolvers.le.acme.email=baptiste.vial@mail.com"
  #     - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
  #   ports:
  #     # Synology : Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use
  #     - 3080:80
  #     - 3443:443
  #   volumes:

  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - letsencrypt:/letsencrypt
  #   networks:
  #     - traefik

volumes:
  user-avatars:
  project-background-images:
  attachments:
  db-data:
  letsencrypt:


networks:
  kanban_db: #traefik:
